### ISSUE TITLE
Position text by X/Y, getFontHeight not precise?

### ISSUE THREAD

**Issue by twoSGmbH** [rospdf/pdf-php#100]
Hello,

i'm trying to positionate a headline at exact coordinates with ezText. X is defined by margin but when i try to pass Y it's positioned a few pixels lower. I found that it's because of the height of the font is not properly determined by getFontHeight. When i set leading (internaly it's set to the height) to the actual height of the text it's positioned properly.

My question/solution is why the texts spacing is added to the top of the text and not the bottom? if it would be added to the bottom then i would be able to position it by X/Y.
Does anyone faced this topic so far?

Thanks in advance
Marius from two S GmbH

**Comment by ole1986** [comment]
Its difficult to answer your question as the typography of a font has several heights and positions.
See https://en.wikipedia.org/wiki/Typeface#/media/File:Typography_Line_Terms.svg

Most common is to calculate the font-height together with its descender to get a proper line break.
This may also help you to calculate the correct position.

It would be helpful to provide us an example of what it does and what you expect to do.
Thank you

**Comment by twoSGmbH** [comment]
![grafik](https://user-images.githubusercontent.com/20795740/40363005-7c52598a-5dce-11e8-83ee-0982b680f832.png)

	//Size 22 is 6mm in heigh,

	$fromTop = $pdf->ez['pageHeight'] - (2 / 2.54 * 72);
	$pdf->line(0, $fromTop, 400, $fromTop);         //Line 2cm from the top
	$pdf->ezSetY($fromTop);
	$pdf->ezText("This text should\nstart at 2cm from the top", 22);

	$pdf->line(10, $fromTop, 10, $fromTop - $pdf->getFontHeight(22));
	//The Font height includes the spacing till the line

	$fromTop = $pdf->ez['pageHeight'] - (6 / 2.54 * 72);
	$pdf->line(0, $fromTop, 400, $fromTop);         //Line 6cm from the top
	$pdf->ezSetY($fromTop);
	$pdf->ezText("This text should\nstart at 6cm from the top", 22, ["leading" => (0.6 / 2.54 * 72)]);
	$pdf->ezStream();

Reducing the text height via leading to the actual font size would solve my problem but then multiline text will no longer have spacing.

I hope this illustration makes my problem clearer now.

**Comment by ole1986** [comment]
The position of the first line starts at `$pdf->getFontHeight($size)` while the font height is calculated via the FontBBox (max height of the largest letter).

If you want to have the first line matching the `CapHeight` (as shown in your screenshot I assume) you need to substract it before `ezText`  takes place.

The most common way people are doing is to subtract the descender as shown below.
`$pdf->ezSetY($fromTop - $pdf->getFontDescender(22));`

Dependent on the font and glyph you are using  this may have side effects and can cause overlapping
