### ISSUE TITLE
Infinite loop when not using utf-8

### ISSUE THREAD

**Issue by Kricke242** [rospdf/pdf-php#107]
Hi! We found a problem with not using utf-8 (but iso 8859-1) and printing åäö. It hangs in an infinite loop and crash. We traced the problem and believe it is two separate bugs. 

First, when calculating the width in the

 `function public getTextWidth($size, $text)` 

it does not utf8_encode first. This result in a $text = null in the following line:

` $text = preg_replace('/<\/?([cC]:|)('.$this->allowedTags.')\>/u', '', $text);`

And as a result, the calculated width is 0, which sets up the second problem.

The second problem is when the width is 0, or to small, for the text, it seems to try to break the text to the next row (always in case of problem 1 above). 

This problem result in the function below does not return "", but always the same text, after its done.

 `public function addText($x, $y, $size, $text, $width = 0, $justification = 'left', $angle = 0, $wordSpaceAdjust = 0, $test = 0)`

And then 
`public function ezText($text, $size = 0, $options = array(), $test = 0)
...
while (strlen($line) || $start) {` 

continues forever. Something like that. 

There may be more to it than this, we are not sure exactly, but this what was we initially found.

Thank you!

**Comment by ole1986** [comment]
Thank you for reporting..
Will have a closer look into it soon.

**Comment by ole1986** [comment]
Hi,

can you please confirm if this still exist in version 0.12.50?

**Comment by ole1986** [comment]
I am sure this is fixed with #115 (version >= 0.12.50)
