### ISSUE TITLE
Add comment(annotate) not working in Php 5.1.6

### ISSUE THREAD

**Issue by anoopkd001** [rospdf/pdf-php#108]
Hi

Is there any way I can get the Cezpdf working from my server with Php5.1.6 to create pdf's with comments/annotations included.I have the old version Ezpdf used in this server,but that does not support  comments I presume.
Can you help?

Thanks
Anoop

**Comment by ole1986** [comment]
We actually support php starting with version 5.4.
Feel free to reopen the issue if you still have problems while using php 5.4 or higher
