### ISSUE TITLE
getTextLength() is causing very high CPU and Memory usage

### ISSUE THREAD

**Issue by teslina** [rospdf/pdf-php#109]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in class/pdfPHP/0.12.48/src/Cpdf.php on line 3127

This error popped up after upgrading from 0.12-rc17 to 0.12.48. 
I tracked it down to this:

When generating a table using ezTable and a line with very long text has to be wrapped, the pdf generation loads forever using almost all CPU and Memory it could get. When the lines are shorter and nothing has to be wrapped, the script runs fine. 

The script is also crashing in version 0.12.45
However, it works fine in version 0.12-rc17

You may use the following test script to reproduce this error:
`<?php
  
//  require_once ('class/pdfPHP/0.12-rc17/src/Cezpdf.php');
//  require_once ('class/pdfPHP/0.12.45/src/Cezpdf.php');
    require_once ('class/pdfPHP/0.12.48/src/Cezpdf.php');
  
    $pdf = new Cezpdf('a4','portrait');

    // settings
    $margin_top 	= 150;  	
    $margin_bottom 	= 80;
    $margin_left 	= 47;
    $margin_right 	= 47;

    $page_width_orig = 595.28;

    $page_width	= $page_width_orig - $margin_left - $margin_right;
    $font_default	= 9;
    
    $pdf->ezSetMargins($margin_top,$margin_bottom,$margin_left,$margin_right);

    // table content
    // causes error
    $data = array(
                array(
                    '<b>Artikel</b>' => 'This is causing a very high CPU Load und Memory Usage. If we have less text which doesn\'t have to be wrapped, the table is being displayed fine. It\'s also working fine in version 0.12-rc17',
                    '<b>Artikel-Nr.</b>' => '001574',
                    '<b>Code</b>' => '',
                    '<b>MWST</b>' => '2.5%',
                    '<b>Preis</b>'     => 'CHF6.60',
                    '<b>Summe</b>' => '13.20'),
                array(
                    '<b>Artikel</b>'  => '2 x Lovechock :: Tafel Schokolade 93% Kakao RAW Bio, 70g',
                    '<b>Artikel-Nr.</b>'          => '002577',
                    '<b>Code</b>' => '',
                    '<b>MWST</b>' => '2.5%',
                    '<b>Preis</b>'     => 'CHF5.70',
                    '<b>Summe</b>' => '11.40')
            );
    
    // this one is working (with shorter text)
    /*
    $data = array(
                array(
                    '<b>Artikel</b>' => 'This is working fine',
                    '<b>Artikel-Nr.</b>' => '001574',
                    '<b>Code</b>' => '',
                    '<b>MWST</b>' => '2.5%',
                    '<b>Preis</b>'     => 'CHF6.60',
                    '<b>Summe</b>' => '13.20'),
                array(
                    '<b>Artikel</b>'  => '2 x Lovechock :: Tafel Schokolade 93% Kakao RAW Bio, 70g',
                    '<b>Artikel-Nr.</b>'          => '002577',
                    '<b>Code</b>' => '',
                    '<b>MWST</b>' => '2.5%',
                    '<b>Preis</b>'     => 'CHF5.70',
                    '<b>Summe</b>' => '11.40')
            );
     */
    // ---------------- BUILD TABLE ------------------ //

    $y = $pdf->ezTable($data,'','',array(
                    'showLines'=>         0,
                    'showHeadings'=>     1,
                    'shaded'=>            2,
                    'shadeCol' =>        array(1,1,1),
                    'shadeCol2' => array(0.9,0.9,0.9),
                    'fontSize' => $font_default,
                    'rowGap' =>         2,
                    'colGap' =>         0,
                    'xPos' =>             'center',
                    'xOrientation'=>    'center',
                    'width' => $page_width,
                    'maxWidth' => $page_width,

                    'cols' =>        array(
                                    '<b>'. TABLE_HEADING_CODE .'</b>' => array('justification'=>'right'),
                                    '<b>'. TAX .'</b>' => array('justification'=>'right'),
                                    '<b>'. PREIS .'</b>' => array('justification'=>'right'),
                                    '<b>'. SUMME .'</b>' => array('justification'=>'right'),
                                     ),
                )

    );

    // pdf output
    $pdf->ezStream(array(
        'Content-Disposition' => '"test.pdf"',
        )
      );             
?>`

**Comment by ole1986** [comment]
Thank you very much for the example.
Will have a closer look into it soon.
