### ISSUE TITLE
Border limits

### ISSUE THREAD

**Issue by ednerbertao** [rospdf/pdf-php#110]
Hi !

I am using arial font on pdf but it not respect the table borders.

	$tmp = array('b'=>'arial_b','bi'=>'arial_bi','i'=>'arial_i');
	$pdf->setFontFamily('arial', $tmp);
	$pdf->selectFont('./includes/fonts/arial', '', 1, true);

'rowGap'=>1,'colGap'=>1, 'fontSize'=>8, 'width'=>570, 'showHeadings'=>0, 'shaded'=>0, 'xPos'=>'center'

![image](https://user-images.githubusercontent.com/7918319/45556247-29cc2680-b811-11e8-9261-02c29b139443.png)

When I try use Helvetica the border OK but the lib don´t understand the special caracters (ã,é,ó,etc)

![image](https://user-images.githubusercontent.com/7918319/45556465-b545b780-b811-11e8-8215-ee619db7555d.png)

![image](https://user-images.githubusercontent.com/7918319/45556532-dd351b00-b811-11e8-8df0-178f2445ed5b.png)

**Comment by ole1986** [comment]
This may indirectly be fixed with v0.12.50.
Any chance, you can confirm?

**Comment by ole1986** [comment]
To workaround for this is properly set the column width as described in issue #118
