### ISSUE TITLE
Bold and Italic is not working

### ISSUE THREAD

**Issue by Manuzza** [rospdf/pdf-php#116]
As the title says. In the latest release (installed via Composer) you cannot both bold and italic text in any font.

Example:

```
$PDF->ezText("<b>".$Text."</b>", 10); // correctly displays bold
$PDF->ezText("<i>".$Text."</i>", 10); // correctly displays italic
$PDF->ezText("<b><i>".$Text."</i></b>", 10); // incorrectly displays italic only
PDF->ezText("<i><b>".$Text."</b></i>", 10); // incorrectly displays bold only
```

I have tested Helvetica, Times-Roman and some external fonts and all are the same.

The issue exists in 0.12.45 through to 0.12.49. When I downgrade to 0.12.44 everything works as expected.

**Comment by ole1986** [comment]
This has something to do with the callbacks being reworked starting with v0.12.45
possible duplicate with #114
