### ISSUE TITLE
ezTable column title problem

### ISSUE THREAD

**Issue by habiloid** [rospdf/pdf-php#117]
Hi
 I have a table set up as so:
` $columns = array("<b>Date</b>", "<b>Training</b>", "<b>Expires</b>", "<b>Comments</b>", "<b>Reason</b>");
$tableOptions = array('showLines'     => 0,
                      'fontSize'      => 10,
                      'maxWidth'      => 535,
                      'shadeCol'      => array(0.8, 0.8, 0.8),
                      'xPos'          => "center",
                      'xOrientation'  => "center");
$pdf->ezTable($tdetails, $columns, "", $tableOptions);`

If the array `$comments` is empty PHP hangs with an 'allowed memory size exhaused'. (It's fine as lone as even one line has a`$comment` set.) 

If I remove `<b>` and `</b>` from the `Comments` column then every thing behaves fine; it doesn't matter if `$comments` is empty or not.

**Comment by habiloid** [comment]
After further experimentation I fount that adding 19 spaces to all the empty elements of `$comments` made the original code work fine. I guess this possibly indicates it a string length problem as 18 spaces led to the same 'allowed memory' problem.

**Comment by ole1986** [comment]
dup with #115
