### ISSUE TITLE
Table columns with <b> or <i> cause the cell to overlap (when no width is defined)

### ISSUE THREAD

**Issue by ole1986** [rospdf/pdf-php#118]
![image](https://user-images.githubusercontent.com/4850116/56222233-f46c0d80-606b-11e9-876e-7686727e2fd0.png)

To workaround this, please manually set the correct width using

**Example**
```

$options = [
   'cols' => [
     '<b>Artikel</b>' => array('justification'=>'right'),
     '<b>Artikel-Nr.</b>' => array('justification'=>'right', 'width' => 47),
     '<b>Code</b>' => array('justification'=>'right', 'width' => 50),
     '<b>MWST</b>' => array('justification'=>'right', 'width' => 40),
     '<b>Preis</b>' => array('justification'=>'right', 'width' => 40),
     '<b>Summe</b>' => array('justification'=>'right', 'width' => 40),
   ],
];

$pdf->ezTable($data, '', '', $options)
```

**Comment by Manuzza** [comment]
I am having a variation on this issue, but it is when using bold text in a cell. It appears that when bold text is placed in a cell that wraps across multiple lines the calculations on how wide the text is appears to be done on the non-bold size of the text. This happens even if the cell is a fixed width.

The first line is generally always correct but the subsequent lines "stick out" past the end of the cell.

Note that sometimes it works and sometimes it doesn't - I have not found what set of circumstances will consistently make it fail.

The only fixes at the moment appear to be removing the bold (which I cannot do) or place individual bold tags around every single like. For example:

`<b>The</b> <b>wrapping</b> <b>text</b> <b>needs</b> <b>to</b> <b>look</b> <b>like</b> <b>this.</b>`

This, as you can imagine, is a bit of a problem.

**Comment by ole1986** [comment]
Have you already tried to put a fixed column width?

**Comment by Manuzza** [comment]
Yes, the problem persists with a fixed column width, but not always. I cannot figure out the exact combination that causes it but as I said, adding separate <b> tags to every single word appears to do the trick...

**Comment by ole1986** [comment]
It might have something to do with spacers. Have you tried putting trim() before passing the string..
Of course this must be fixed from the library side. But at least a trim would be much more comfortable then wrapping every word with bold tags

**Comment by Manuzza** [comment]
Dammit - some of my tests were done on an older version (0.12.44) which works. I can now replicate the issue every time. I have created a new task for this which is #127 which includes a sample script and generated PDF showing the issue.
