### ISSUE TITLE
Function uniord() keeps given notices

### ISSUE THREAD

**Issue by enfoqueNativo** [rospdf/pdf-php#120]
After updating to 0.12.50 i've started to get log files filled with this notice
`PHP Notice:  Uninitialized string offset: 0 in /srv/si/vendor/rospdf/pdf-php/src/Cpdf.php on line 3088`

It seems uniord only receives one character. Could a conditional be added to handle several use cases?

Regards

**Comment by ole1986** [comment]
@enfoqueNativo thank you for reporting

Can you please provide me with some more information (PHP version, fontname being used, etc..) including an example?

Thank you in advanced

**Comment by ole1986** [comment]
@enfoqueNativo can you please provide me with at least the font you are using?
