### ISSUE TITLE
ezTable/addText bug out if a newline is required to fit the text passed into either function if the text contains <b>,<i>, or <strong>

### ISSUE THREAD

**Issue by kevinsdb** [rospdf/pdf-php#123]
I've come across an ezTable/addText bug that has been in the past 2 releases 0.12.50/0.12.51.
I've attached a file that creates a simple PDF that shows the bug I'm talking about.
If the text string passed to either function has any of the special characters to bold or italicize it, it will ignore the width you set and not create a newline.

[test_pdf.txt](https://github.com/rospdf/pdf-php/files/3174881/test_pdf.txt)

**Comment by ole1986** [comment]
Thank you for reporting and for the sample code.
Going through this and fix it with the next update
