### ISSUE TITLE
Top Table Border drawn too high

### ISSUE THREAD

**Issue by Manuzza** [rospdf/pdf-php#125]
The top border of the table is being drawn too high. This example is from pdf-php being installed vi composer as below:

```
{
    "require": {
        "rospdf/pdf-php": "^0.12.52"
    }
}
```

The old version (the original code from many, many years ago) works perfectly. A screen shot of both is attached as well as sample code to test it. Attached is also a generated PDF as from the sample code.

You can see from the screenshots that they text above, below and IN the table are in the exact same spot, but the border moves. This is especially evident when you have a collared page and a white fill in the table cells (as we are using here). The fill stops in the correct location but the border is not in the same place.

[generated.pdf](https://github.com/rospdf/pdf-php/files/3390788/generated.pdf)
![New Library (Wrong)](https://user-images.githubusercontent.com/476640/61194623-08281e00-a706-11e9-8b9c-5ac591fce2af.png)
![Old Library (Correct)](https://user-images.githubusercontent.com/476640/61194628-1118ef80-a706-11e9-9769-68af139ebbe7.png)
[sample.txt](https://github.com/rospdf/pdf-php/files/3390789/sample.txt)

Can this be fixed please?

**Comment by Manuzza** [comment]
I believe I have found the issue. I have created a new branch called Issue_125 and pushed the potential fix there. The fix is changing the same line (twice) in Cezpdf::ezTable(). I have also commented out and and marked the old line so you can find it easily. The lines are as follows:

```
//          $y0 = $y + $descender; // REPLACED THIS LINE WITH THE FOLLOWING
            $y0 = $y - $options['rowGap'];
```

Manuzza

**Comment by ole1986** [comment]
Looking good to me, thank you
