### ISSUE TITLE
Table Issues: Bold Alignment and Missing Colour

### ISSUE THREAD

**Issue by Manuzza** [rospdf/pdf-php#127]
[generate.txt](https://github.com/rospdf/pdf-php/files/3429203/generate.txt)
[generated.pdf](https://github.com/rospdf/pdf-php/files/3429204/generated.pdf)

This is more detail regarding issue 118:

When using release 0.12.53 (installed vi composer) I have the following two issues:

Setting "textCol" on a table is ignored. The sample is supposed to have red text in the tables.

When text is in bold the alignment on any line past the first is wrong. It appears as though the width of the text is calculated using the non-bold equivalent. However adding bold tags to every individual word (rather than the whole paragraphs) appears to address this issue.

The attached sample code (and generated PDF) shows all of this.

Manuzza

**Comment by savioret** [comment]
I can confirm that this problems occurs after any of the fixes of release 0.12.50
More exactly on commit 0ac7c85 for issue #114 
I reverted just the code affecting `addText` and the problem disappeared.

**Comment by ole1986** [comment]
I might have fixed this by move the `foreach`in addText above addTextWithDirectives.

Try out the patch with `git apply issue-127.patch(.txt)` and let me know. Thank you

[issue-127.patch.txt](https://github.com/rospdf/pdf-php/files/3438023/issue-127.patch.txt)

**Comment by Manuzza** [comment]
I have tested the patch and the bold alignment issue is fixed (thank you). Unfortunately there is no change to the missing text colour (as defined by the TextCol table option). Any chance this also could be addressed?

**Comment by ole1986** [comment]
I think the 'textCol' you mention is for the header row only.
Header row is given in `$pdf->ezTable($data, [here], [...])`;

But there are good news. You can also add individual colors per field using the magic field suffixes `<column>Fill` and `<column>Color`.

I have slightly amended the [table-enhancements.php example](https://github.com/rospdf/pdf-php/blob/master/examples/table-enhancements.php) containing almost all possible coloring options.

**Comment by savioret** [comment]
Thanks for the patch @ole1986 
However that code breaks the underline for centered texts.

![image](https://user-images.githubusercontent.com/5497332/62003816-f474b280-b11c-11e9-920d-50a58d90db50.png)

**Comment by Manuzza** [comment]
Regarding 'textCol': it used to change the colour of all the text in the table. I have gone back to an older version and tested the sample I provided. I can also confirm the the text colours used in tables are not all black when they used to be in color.

**Comment by ole1986** [comment]
been busy these days but will try to fix it asap.

Any help appreciated

**Comment by Manuzza** [comment]
I have fixed the colours in a branch I just used called Issue_127. It looks like all of the code that sets the text colours went missing for some reason. There are two sources of text color - the textCol for the table (default) and an individual colour for the specific cell. Both were being ignored.

I found the code in an older branch and copied it back in (I did not actually write any new code - just inserted old and unchanged code).

For reference the individual cell colours for the background of each cell was working correctly so that code was still present.

**Comment by ole1986** [comment]
Can someone by chance double check it by using the master branch?

**Comment by Manuzza** [comment]
All aspects of color and alignment are working for Bold text. However underline across multiple lines is now broken. Attached is Bold.pdf (current) Underline.pdf (incorrect) and sample code to replicate this.

Note the Underline file is only incorrect with regards to the underline itself - color and alignment is all good.

[generate.txt](https://github.com/rospdf/pdf-php/files/3449212/generate.txt)
[Underline.pdf](https://github.com/rospdf/pdf-php/files/3449213/Underline.pdf)
[Bold.pdf](https://github.com/rospdf/pdf-php/files/3449214/Bold.pdf)

**Comment by Manuzza** [comment]
I just tested this and it is PERFECT. Thank you! AND I see that composer libraries have a new version. A second THANK-YOU!
