### ISSUE TITLE
Infinite loop when a word does not fit a cell

### ISSUE THREAD

**Issue by savioret** [rospdf/pdf-php#129]
The infinite loop occurs when a single word is wider than the cell width
This is the simplest example to reproduce it
```php
$pdf = new Cezpdf('a4', 'portrait');

$myoptions = array(
    'showHeadings'=>0,
    'cols' => [['width' =>44]]
);
$data = [['BBBBBBBB']];
$pdf->ezTable($data, '', '', $myoptions);
$pdf->ezStream();
```

There's also a notice which appears in each iteration. The `$c` variable passed at
 `$cOrd = $this->uniord($c);` 
is an empty string.
```
A PHP Error was encountered
Severity: Notice
Message: Uninitialized string offset: 0
Filename: pdf-php/Cpdf.php
Line Number: 3115

File: Cpdf.php
Line: 2854
Function: uniord

File: Cpdf.php
Line: 3011
Function: addTextWithDirectives

File: Cezpdf.php
Line: 1747
Function: addText
```

Please, let me know if you need more information about the issue.
Thank you.

**Comment by ole1986** [comment]
Is the latest commit on master branch working for you?

**Comment by savioret** [comment]
Sorry, I still had no time to validate the update.

**Comment by savioret** [comment]
Tested.
It's working like a charm. Thank you so much.
