### ISSUE TITLE
Underline not terminating in multi line situation

### ISSUE THREAD

**Issue by tcowin** [rospdf/pdf-php#132]
In version 0.12.55, using underline where it spans lines, after the underline is complete, the line does not terminate, but goes directly to the origin at lower left corner.

Thanks!

<img width="741" alt="Screen Shot 2019-09-08 at 3 45 33 PM" src="https://user-images.githubusercontent.com/1229114/64495547-65e16e00-d250-11e9-8523-99fc9e643702.png">
<img width="1414" alt="Screen Shot 2019-09-08 at 3 41 45 PM" src="https://user-images.githubusercontent.com/1229114/64495558-8a3d4a80-d250-11e9-8794-b06c1190777b.png">

**Comment by ole1986** [comment]
I could not reproduce it with my lines of code. Can you provide me with your example source please?

**Comment by ole1986** [comment]
@tcowin any chance I can get your example code?

**Comment by tcowin** [comment]
@ole1986  Thanks for looking at this and sorry for the delay...

[pdfgen.txt](https://github.com/rospdf/pdf-php/files/3635973/pdfgen.txt)
[abstracts_presentation_53146.pdf](https://github.com/rospdf/pdf-php/files/3635974/abstracts_presentation_53146.pdf)

**Comment by tcowin** [comment]
@ole thanks!

**Comment by ole1986** [comment]
**side note**

The example given by @tcowin requires to use a proper unicode font (like FreeSerif) to display the character "μ" correctly.

Also it is necessary to apply a font family for this font to support *bold*

```
// [...]
$pdf->isUnicode = true;

$pdf->setFontFamily("FreeSerif", [
    'b' => 'FreeSerifBold'
]);

$pdf->selectFont('FreeSerif');
$pdf->ezText("[some unicode text wit full justification]", 9, ['justification' => 'full']);
// [...]
```
