### ISSUE TITLE
Force PDF download

### ISSUE THREAD

**Issue by feramos60** [rospdf/pdf-php#135]
Buen día
He estado tratando de forzar la descarga en el navegador del PDF generado y no logro hacerlo con ezOutput o ezStream.
Agradezco su ayuda

Good day
I have been trying to force the download in the browser of the generated PDF and I can't do it with ezOutput or ezStream.
I appreciate your help

**Comment by ole1986** [comment]
Hi,

have you already tried  `$pdf->ezStream(['download' => 1]);` ?

**Comment by feramos60** [comment]
Hello
I already tried and it doesn't work.
Just open it in the browser but don't download it.
