### ISSUE TITLE
Missing release notes for rc18 and rc19

### ISSUE THREAD

**Issue by lsolesen** [rospdf/pdf-php#14]
There is no release notes for the two most recent releases rc18 and rc19 in `experimental` readme.pdf.

**Comment by ole1986** [comment]
release notes?
the below is included into the [readme.pdf](https://github.com/ole1986/pdf-php/blob/master/readme.pdf) 
0.12-rc19
- applied patch "updated extension CezTableImage" from Code Snippets forum - thanks Sigurd Nes
0.12-rc18
- fixed reported bug #77 ezText html bold tag problem

**Comment by ole1986** [comment]
Also I want to get rid of this "rcXX" thing...
I would prefer a version number similar to <MAJOR, MINOR, PATCH> (example 0.12.19 for the latest version)

**Comment by lsolesen** [comment]
I think we should just release 0.12.0. Rc i release candidate. By doing
0.12.0 people will know it is considered stable.

After thinking more about it I think we should tag 0.12.0 already now with
release notes saying that it will be the last of that series and what is
going to break in the next version, like php 5.4 is required.

Den ons. 11. maj 2016 16.06 skrev ole <notifications@github.com>:

**Comment by lsolesen** [comment]
Regarding the release notes, I meant in the experimental version.

**Comment by ole1986** [comment]
I would keep it with version 0.12.X and also write this into readme.pdf (no rc suffix).
For the experimental readme I would truncate everything and start the changelog from 0.13.0 until 0.13.X.

**Comment by ole1986** [comment]
not sure why this ticket is still opened.
We will continue using version 0.13.X fpr the upcoming (experimental) version.
0.12.X is the current stable.
