### ISSUE TITLE
Add custom font

### ISSUE THREAD

**Issue by aksld** [rospdf/pdf-php#144]
Hi,

Where, please, can I find a guide to add custom font ?

I just have one file for regular and one file for bold.

Thanks for helping

**Comment by ole1986** [comment]
You may look at the [unicode.php](https://github.com/rospdf/pdf-php/blob/master/examples/unicode.php) example which uses font families

1. Add your fonts (regular and bold) into the `src/fonts/` directory
2. Build up the font family using `pdf->setFontFamily($mainFont, $family);` - see readme.pdf
3. Select the regular font with `$pdf->selectFont($regularFont, [...]);`
4. use the bold font style with "<b></b>" when using `$pdf->ezText([...])`

**Comment by aksld** [comment]
Thanks for help !

This is my code :

`
$this->fontPath    = ACD_FLIGHTS_MANAGEMENT_DIR . 'assets/fonts';
	
		$mainFont = 'Gotham';

		$family = array(
			'b'=> 'Gotham-Bold'
		);

		$pdf->setFontFamily( $mainFont, $family );

		// select a font and use font subsetting
		$pdf->selectFont( $mainFont, '', 1, true );
`

I think that something is missing.

How can I specify the path for my font ?

I have two files :
- Gotham.tff
- Gotham-Bold.tff

**Comment by ole1986** [comment]
The default font path is given in the constructor:
https://github.com/rospdf/pdf-php/blob/master/src/Cpdf.php#L435

you can change it like shown below
```
$pdf->fontPath = './myfonts';
```

**Comment by aksld** [comment]
ok perfect, thanks :)

Do you know if I can do something like that :

![rounded-1](https://user-images.githubusercontent.com/6853619/81583707-0248ab00-93b2-11ea-8e14-6f2d48fbbbc3.png)

Thank you for helping
