### ISSUE TITLE
Naming confusion

### ISSUE THREAD

**Issue by lsolesen** [rospdf/pdf-php#15]
- The library is named R&OS PDF PHP library.
- The main class is called Cpdf.
- It is on ole1986/pdf-php

It seems a little odd. I would probably think the library is best known as Cpdf, but I am not sure.

We could do a couple of things to remedy this? We could create an organization on github, which hosts the library. That organization could be named `cpdf` and then the repository could still be `pdf-php`.

The repository could also be renamed to `cpdf-php`.

For `composer` right now it is called `randos/pdf-php`. This should also be renamed to whatever, we choose to be the name of the organization. 

If we choose to use namespacing we should choose a good one :)

@ole1986 What is your take on this one?

**Comment by ole1986** [comment]
as namespace I would prefer to use "ROSPDF" as this is the main name of this project.
So we can continue using the class Cpdf without an repeating names

Both names are actually known and cannot be avoided.

**Comment by ole1986** [comment]
So what you think of doing a github organisation named "https://github.com/ROSPDF" (ROSPDF) ?

**Comment by lsolesen** [comment]
Lowecase will be perfect

Den tor. 12. maj 2016 16.23 skrev ole <notifications@github.com>:

**Comment by ole1986** [comment]
So you want me to transfer everything to the newly created organisation?

**Comment by lsolesen** [comment]
I think it is possible with the click of a button in github admin.

Den tor. 12. maj 2016 16.59 skrev ole <notifications@github.com>:

**Comment by ole1986** [comment]
Done!

But namespace in version 0.13 will be written uppercase of course. And class names in CamelCase if possible I think

**Comment by lsolesen** [comment]
Cool. You can remove the exclusion of the rule from phpcs.xml when fixing.

Den tor. 12. maj 2016 17.14 skrev ole <notifications@github.com>:

**Comment by ole1986** [comment]
Closing it... Building up namespaces take part in issue #22
