### ISSUE TITLE
Spot colour

### ISSUE THREAD

**Issue by pjaucamp** [rospdf/pdf-php#154]
HI, I would like to make an automated label designer and output as a A4 pdf. All the functions is already good as is except for one last thing that I will need. I need to include a cutting line for my print software. To do that you simply draw a line or box and give the outline color a NAME and the colour type must be a SPOT colour. How will one accomplish this? Simply setting a colour the way it is done now is not enough.

**Comment by ole1986** [comment]
Any chance you can provde an image on how you expect to have it look like?

**Comment by pjaucamp** [comment]
Hi,

Basically I will just need to "name" the outline colour and it must be a
spot colour type, but how that gets encoded into the pdf I have no idea.
See screenshot of how I would do this in illustrator.

[image: image.png]

Thank you so much!
Pieter

**Comment by ole1986** [comment]
```
$angle = 0;
// draw text
$pdf->addText($x, $y, $fontSize, "Text", 0, 'left', $angle)

// prepare line to be dotted
$pdf->setLineStyle(5, '', '', [5]);
// draw the line
$pdf->line($x, $y, $x + 100, $y + 100)
```
