### ISSUE TITLE
Is R&OS still maintained?

### ISSUE THREAD

**Issue by AlainCNpt** [rospdf/pdf-php#158]
Hi,
I've been using R&OS pdf for many years, but now I have some requirements that aren't available... and it seems R&OS isn't  maintained anymore.  In other projects, I found a more recent version of Cpdf (eg. with the addition of forms & signatures as used in dompdf), but it's not completely replaceable.  
Are there still changes planned?  I might try to mix both files to a working version for me (but I don't need all features, so I won't be able to make a fully tested upgrade), I can share info on this if it seems useful...
BR,
Alain

**Comment by ole1986** [comment]
To be honest it's being hard these days to maintain due to lack of time!

Trying to get ppl. around to participate but yet no guarantee to get some involved

**Comment by savioret** [comment]
Hello @AlainCNpt did you manage to add an updated version of Cpdf to work with forms ?
I'd be highly interested into that.

**Comment by savioret** [comment]
Thank you so much for the quick response Alain.
I'll have a deeper look at that, but the modifications you did seem quite neat.
I'm doing an extensive use of the library so, I'll try to adapt that similarly, and if that passes the tests, and my own pdf tests, I may push that into a fork.
