### ISSUE TITLE
Create an index of contents with page numbers

### ISSUE THREAD

**Issue by savioret** [rospdf/pdf-php#169]
Hello,
I'm trying to build a document with a "list of contents" index with numbers. I've been able to link every section of its page using annotations.
However I'd like somehow to get the page number printed, I don't know if there is a way to do that.
No need to mention that the document is dynamic and I don't know in advance which page number each section starts.

If as I'd expect, there's not such way to do it, I was thinking that I could create the index as the last page of the document as I can save when every different section started, the challenge would be moving that last page to the first position, which also I'm not sure if it's possible.

Any help or suggestions are welcome.
Thanks.

**Comment by ole1986** [comment]
The readme.php generating the readme.pdf does exactly what you search for
