### ISSUE TITLE
Improve examples in version 0.12

### ISSUE THREAD

**Issue by ole1986** [rospdf/pdf-php#17]
Can you please get over the examples folder of the current release

- pdftomail.php (should be removed)
- image.php (should be improced - at least a different color)
- imageInTable.php (should be moved to tables.php)
- imageObjectHash.php (must be more clear on what is happening here - technically its working)
- tables.php (good so far, but add the inline image examples from imageInTable.php here)
- test.php (move it to fonts.php and need more investigation on encodings i guess)
- unicode.php
- unicode-file.php (move it to unicode.php)

Thank you

**Comment by lsolesen** [comment]
I dont think we should spend more time on 0.12 unless stuff is not working.

Den tor. 12. maj 2016 17.30 skrev ole <notifications@github.com>:

**Comment by ole1986** [comment]
Those versions have major differences.. And as you already mentioned version 0.13 becomes major impact on its php version I would keep the previous version as clean as possible. 

That's why I still think it makes sense to update examples in version 0.12 as well

Thank you

**Comment by ole1986** [comment]
at least I change the color in the image examples.... lets close this ticket!
