### ISSUE TITLE
Save PDF on local server

### ISSUE THREAD

**Issue by masterbuga1212** [rospdf/pdf-php#170]
I wanted to congratulate first of all for the excellent product.
It's amazing!

I can't find in the documentation how to save the PDF file created with Stream, in a local folder of the web server.

I don't want to think it's not possible.
That would be a shortcoming

**Comment by oradwell** [comment]
Hi @masterbuga1212 You can use `$pdf->ezOutput()` (instead of "stream") to get the contents to create a file. The following should work:
```php
file_put_contents('/path/to/file', $pdf->ezOutput());
```

**Comment by masterbuga1212** [comment]
Thank you very much!! it works!
Regards
