### ISSUE TITLE
PHP 8.1 Incompatible

### ISSUE THREAD

**Issue by lnaranj0** [rospdf/pdf-php#171]
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in vendor\ros\ezpdf\src\Cpdf.php on line 3078

PHP 7
private function uniord($c)
    {
        // important condition to allow char "0" (zero) being converted to decimal
        if(strlen($c) <= 0) return false;
        $ord0 = ord($c{0}); if ($ord0>=0   && $ord0<=127) return $ord0;
        $ord1 = ord($c{1}); if ($ord0>=192 && $ord0<=223) return ($ord0-192)*64 + ($ord1-128);
        $ord2 = ord($c{2}); if ($ord0>=224 && $ord0<=239) return ($ord0-224)*4096 + ($ord1-128)*64 + ($ord2-128);
        $ord3 = ord($c{3}); if ($ord0>=240 && $ord0<=247) return ($ord0-240)*262144 + ($ord1-128)*4096 + ($ord2-128)*64 + ($ord3-128);
        return false;
    }

PHP 8
private function uniord($c)
    {
        // important condition to allow char "0" (zero) being converted to decimal
        if(strlen($c) <= 0) return false;
        $ord0 = ord($c[0]); if ($ord0>=0   && $ord0<=127) return $ord0;
        $ord1 = ord($c[1]); if ($ord0>=192 && $ord0<=223) return ($ord0-192)*64 + ($ord1-128);
        $ord2 = ord($c[2]); if ($ord0>=224 && $ord0<=239) return ($ord0-224)*4096 + ($ord1-128)*64 + ($ord2-128);
        $ord3 = ord($c[3]); if ($ord0>=240 && $ord0<=247) return ($ord0-240)*262144 + ($ord1-128)*4096 + ($ord2-128)*64 + ($ord3-128);
        return false;
    }

**Comment by oradwell** [comment]
Hi @lnaranj0, thanks for your issue. Having looked at the code snippet and error, I think you have an old library version. The "uniord" function is much different now, and it doesn't use curly brace syntax:
https://github.com/rospdf/pdf-php/blob/master/src/Cpdf.php#L3092
