### ISSUE TITLE
divide all classes, use autoload feature and namespace "ROSPDF"

### ISSUE THREAD

**Issue by ole1986** [rospdf/pdf-php#22]
Let us use the feature of spl_autoload_register to dynamically load the class in version 0.13

Before doing this we should of course divide them into single files and properly add the namespace "ROSPDF".

**Comment by lsolesen** [comment]
@ole1986 When using composer for your dependency management you do not even have to have an autoloader installed in the project. It could be left up to the individual developer on how they choose to include the library. We can provide an example on how to do it with spl_autoload_register, but do not have to force it on the developer.

**Comment by ole1986** [comment]
I need to get more into detail of composer ... But to be honest I still like the idea to have it autoloaded.

Just because when we divide the classes now into single files ppl have add all files using `include` or build up/copy the autoloader script.

But what I want is, when I get it either through composer or through git clone... it must work!

**Comment by ole1986** [comment]
Also, composer should be an alternative to git clone and not the first choice of "installing" this library.
So, we should focus more on an explanation when using git clone IMO.

**Comment by ole1986** [comment]
I am thinking of possible namespaces... But actually in my mind I only have one namespace and rest are class names

So, everything would start with:

```php
// file: Cpdf.php
namespace ROSPDF;
class Cpdf { /* contains common methods */ }

// file: CpdfTable.php
namespace ROSPDF\TextFlow // or ROSPDF\TextFormat
class CpdfTable { /* containing methods to add tables cell,rows, etc... */ }

// file: CpdfAnnotation.php
namespace ROSPDF\TextFlow // or ROSPDF\TextFormat
class CpdfAnnotation { /* containing methods to add comments, links, etc..?! */ }

// file: CpdfGraphic.php
namespace ROSPDF\Drawing
class CpdfGraphic { /* containing Border, Line, Rectangle, ... methods */ }

// file: CpdfImage.php
namespace ROSPDF\Drawing
class CpdfImage { /* containing methods to add png,jpg,... images */ }

// file: CpdfCrypt.php
namespace ROSPDF\Security
class CpdfCrypt { /* containing encryption methods */ }

// [...] more might follow
```

Any other ideas?

**Comment by lsolesen** [comment]
I dont think the classes needs to be prefixed with Cpdf, but that is up to
you.

I am not sure whether more namespaces is needed, but it might provide more
clarity. Think names for the namespace i well thought out if more
namespaces are needed.

Den lør. 14. maj 2016 22.09 skrev ole <notifications@github.com>:

**Comment by ole1986** [comment]
Classes and namespaces applied in version 0.13
