### ISSUE TITLE
Add information about installation, e.g. with composer in README.md

### ISSUE THREAD

**Issue by lsolesen** [rospdf/pdf-php#3]
See e.g. http://github.com/lsolesen/pel on how the passage can be written.

**Comment by ole1986** [comment]
FYI: https://travis-ci.org/ole1986/pdf-php

**Comment by ole1986** [comment]
for what does it need the below in composer.json?
`"require-dev": {
        "squizlabs/php_codesniffer": "2.*"
    }`

**Comment by lsolesen** [comment]
The require-dev will aid when developing. Here we include a library capable of checking coding standards.

**Comment by ole1986** [comment]
> The require-dev will aid when developing
but for what is this needed ->: squizlabs/php_codesniffer

Still receiveing: "No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)"

**Comment by lsolesen** [comment]
Yeah. It is because the .travis.yml file was not added when you enabled the tests. I've added it in this commit https://github.com/ole1986/pdf-php/commit/6f16a4c0e14c67a0490959072c3cf186d1bf32f0

However, for some reasons Pushes are disabled now on Travis? -- https://travis-ci.org/ole1986/pdf-php/requests (did you change anything?)

**Comment by lsolesen** [comment]
Checkout https://github.com/ole1986/pdf-php/issues/7
