### ISSUE TITLE
Spot colour

### ISSUE THREAD

**Issue by pjaucamp** [rospdf/pdf-php#32]
Is it possible to set the line colour to a spot colour and define a specific name for it? This will be handy for me to automatically generate a cutting line for my print driver for the artwork to automate the printing process from my website. And a rectangle with rounded corners, is that possible?

**Comment by ole1986** [comment]
To change colors you can use `setColor(r,g,b,[force=0])` and `setStrokeColor (r,g,b)`

Then use `line(x1,y1,x2,y2)` to draw a line.
Customize the line by using `setLineStyle([width],[cap],[join],[dash],[phase])`

For more info check out the documentation - Base class Functions

**Comment by ole1986** [comment]
A possible feature request "Rounded corners"

**Comment by ole1986** [comment]
Also, colors can be defined in table cells using the column name plus Color or Fill suffix.
Example can be found in "examples/table-enhancements.php"

**Comment by ole1986** [comment]
New feature will only take place in version 0.13.X
Closing this issue.
