### ISSUE TITLE
polish characters not working

### ISSUE THREAD

**Issue by twoSGmbH** [rospdf/pdf-php#33]
Hello,

we're a software company from Germany and we really appreciate your work on this project.
Unfortunately we can't get polish or russian characters to work. In the experimental branch 0.13 this issue seems to be fixed because everything works fine. Sadly we're not able to upgrade to 0.13 yet because many features we're using in our current version (0.9) are not implemented in 0.13 yet.

Our question is: if you could bring the character and font support from 0.13 to 0.12 so we can upgrade our software to 0.12, that would be great.

![cezpdf_char_unterschiede](https://cloud.githubusercontent.com/assets/20795740/17356092/9c6f0f3a-5955-11e6-9d45-0f9f06ce7c70.png)

**Comment by ole1986** [comment]
@twoSGmbH welcome to github!

Most common issue is that the font you are using does not support the characters.
In version 0.12 we have included a font which has more support for UTF-8 - Its FreeSerif.

Example for version 0.12:
```php
error_reporting(E_ALL);
set_time_limit(1800);
set_include_path('../src/' . PATH_SEPARATOR . get_include_path());

include 'Cezpdf.php';

$pdf = new Cezpdf('a4','portrait');
$pdf->ezSetMargins(20,20,20,20);

// important to enable UTF-8 encoding
$pdf->isUnicode = true;

$mainFont = 'FreeSerif';
// select a font and use font subsetting
$pdf->selectFont($mainFont, '', 1, true);
$pdf->ezText("\nPolish:");
$pdf->ezText("ąćęłńóśźż");

// The below is using Arial.TTF (keep in mind Arial is licensed by Microsoft)
$pdf->selectFont('../src/fonts/arial');
$pdf->ezText("\nPolish:");
$pdf->ezText("ąćęłńóśźż");

if (isset($_GET['d']) && $_GET['d']){
  echo $pdf->ezOutput(TRUE);
} else {
  $pdf->ezStream();
}
```

**Comment by twoSGmbH** [comment]
@ole1986 Thank you so much, with your comment and especially with the isUnicode hint we're able to get polish characters to work.
