### ISSUE TITLE
Text truncated while wrapping

### ISSUE THREAD

**Issue by p23allan** [rospdf/pdf-php#36]
Hello,
I'm facing this problem where text being truncated while wrapping.
Same issue happened in your readme.pdf in 
Page 14
Page 18
Page 23
Page 29
I think all these pages are having similar problem.
Thank you.

**Comment by ole1986** [comment]
@p23allan thank you for reporting!

checking the readme.php but could not find truncated - Can you please be more specific?
What version are you using?

**Comment by p23allan** [comment]
Hello Ole,

I've attached the 4 pages with red boxes for your reference and kind 
attention.
Thank you.

Best regards,
Allan Chan

**Comment by p23allan** [comment]
These are the attachments
![page14](https://cloud.githubusercontent.com/assets/22670358/19208436/65cb1860-8d2c-11e6-94d4-273011a673de.jpg)
![page18](https://cloud.githubusercontent.com/assets/22670358/19208447/79b7b7b6-8d2c-11e6-8953-dc390a1fa99e.jpg)
![page23](https://cloud.githubusercontent.com/assets/22670358/19208454/8c28e5dc-8d2c-11e6-86ef-d330dbfcb949.jpg)
![page28](https://cloud.githubusercontent.com/assets/22670358/19208527/d0af54f6-8d2d-11e6-9f27-3b89a3e4d842.jpg)

**Comment by ole1986** [comment]
Thank you for reporting.
fixed issues in all pages, except page 28 - [patch here](https://gist.github.com/ole1986/ff3aca0070e3ab04864e94c7a81b7cc9)

In page 28 (setFontFamily) is the callback the reason I guess - Have to investigate more time to fix it as well

**Comment by p23allan** [comment]
Thank you Ole. I'll try and update the results.
