### ISSUE TITLE
fopen font issue

### ISSUE THREAD

**Issue by surealius** [rospdf/pdf-php#37]
Our web server started throwing these errors when generating a pdf with php-pdf. It worked fine with no errors until yesterday. The path "fopen(/tmp/cachedTimes-Roman.php)" looks wrong to me, it isn't the path to the font file in php-pdf tree, perhaps it is a tmp/ copy of the font? The pdf still generates fine. Error still happens when I comment out the font selection statement. Unsure why this issue started or how to fix it. Also concerned that it just started seemingly on its own.

Warning: fopen(/tmp/cachedTimes-Roman.php) [function.fopen]: failed to open stream: Permission denied in /home/site/public_html/include/pdf-php/src/Cpdf.php on line 2039

Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/site/public_html/include/pdf-php/src/Cpdf.php on line 2040

Warning: fclose() expects parameter 1 to be resource, boolean given in /home/site/public_html/include/pdf-php/src/Cpdf.php on line 2041

**Comment by ole1986** [comment]
@surealius the reason why you receiving such "error" (actually its a warning) is that for some reason the php instance cannot access the font cache...

You can change the location of the font cache using `$pdf->tempPath = 'new location';` if need

**Comment by ole1986** [comment]
Closing the issue as this is a matter of configuration
