### ISSUE TITLE
Problem when mixing fonts in a paragraph

### ISSUE THREAD

**Issue by gDanix** [rospdf/pdf-php#38]
Version: 0.12.23

Paragraphs with different fonts (i.e. containing some text in bold or italic) are rendered incorrectly.

Example 1 (<bniel must be draw as "Daniel"):
![captura de pantalla de 2016-10-20 16-15-34](https://cloud.githubusercontent.com/assets/1117657/19563507/875a579e-96e0-11e6-9b8e-24ea6e37c78d.png)

Example 2 (This is what happens inserting a space between \<b\> and Daniel):
![captura de pantalla de 2016-10-20 16-16-58](https://cloud.githubusercontent.com/assets/1117657/19563544/a62df77a-96e0-11e6-8a5a-00493a653aff.png)

**Comment by ole1986** [comment]
Hi and welcome,
can you please provide me an example code on how you change the font being used?

**Comment by gDanix** [comment]
Hi!

Sorry, I forgot to provide that information. Those documents are generated with this script: https://github.com/gDanix/Serg.io/blob/master/master/docencia_externo/docencia_externo.php

This project is in a very early development state, this is the cause for the directory tree to be so confusing, it mixes configuration data and code. (Sorry and thank you!!)

**Comment by ole1986** [comment]
@gDanix currently workin on it - master branch has some important fixes already

But still the justification does not work properly in this version

**Comment by gDanix** [comment]
@ole1986 Thank you very very much.

I'd like to contribute to this library, because it's so useful, but unfortunately I don't have very much free time.

**Comment by ole1986** [comment]
@gDanix almost fixed the justification in current master

Only missing issue is a white space at the end of the line (justify right/full)
Make sure you are also updating the fonts (*.afm files)

**Comment by ole1986** [comment]
This issue should be fixed in PR #39
