### ISSUE TITLE
PHP errors/ warnings when using TTF fonts.

### ISSUE THREAD

**Issue by csiwek** [rospdf/pdf-php#46]
Hi,
I'm getting  notice  'String offset cast occurred'

but also something like that: 

Severity: Warning
Message: Illegal string offset '44.0000000000'
Filename: include/TTF.php

I did cast all $off  variables to int   in TTF.php  and it seem to fix the issue but I'm not sure if that's the right way.

php -v
PHP 5.4.45-0+deb7u5 (cli) (built: Aug 30 2016 20:15:34)

**Comment by ole1986** [comment]
Thank you for reporting, I will have a closer look soon

**Comment by ole1986** [comment]
@csiwek can you please tell us what font you are trying?

**Comment by csiwek** [comment]
@ole1986  it was the FreeSerif from repository:

(notation from codeigniter)  
`
$this->load->library('cezpdf');
$this->cezpdf->isUnicode = True;
$this->cezpdf->selectFont('FreeSerif', '', 1, true);
`

**Comment by ole1986** [comment]
Tests made on PHP7.1 as well as php 5.6 without a problem...

**Comment by ole1986** [comment]
Closed, not reproducible!
