### ISSUE TITLE
Latin characters displayed as question mark

### ISSUE THREAD

**Issue by enfoqueNativo** [rospdf/pdf-php#50]
Latin characters (specifically ó, í, á) are getting displayed as question mark on v 0.12.29.
I tried different fonts, but the same result always.
Os: OpenSuse Leam 42.2
PHP: 5.6.29 [repo](http://download.opensuse.org/repositories/devel:/languages:/php/openSUSE_Leap_42.2/)

Attached code example used to generate PDF file.
[creacion_pdf_manual.txt](https://github.com/rospdf/pdf-php/files/683187/creacion_pdf_manual.txt)

**Comment by ole1986** [comment]
Try using `utf8_encode ( string $data )`

More info: http://php.net/manual/de/function.utf8-encode.php

**Comment by enfoqueNativo** [comment]
Thanks that solved the issue.
