### ISSUE TITLE
Font setup is not well explained.

### ISSUE THREAD

**Issue by rokyed** [rospdf/pdf-php#51]
First of all, I am amazed by the work you all did. I am trying to understand how to set the font ( custom TTF font, Roboto from google).
It seems the font was loaded, yet no visual queue, nor a filesize change is visible. I must be doing something wrong.

```php
$this->isUnicode = true;
$this->setFontFamily("Roboto-Regular", array(
	"b"=>"Roboto-Bold",
	"i"=>"Roboto-Italic",
	"bi"=>"Roboto-BoldItalic",
	"ib"=>"Roboto-BoldItalic",
	"bb"=>"Roboto-Black"
));
$this->selectFont("Roboto-Regular");
```

Please, can you show me an example of how to use the custom TTF fonts?

**Comment by ole1986** [comment]
@rokyed when defining the font family you have the benefit of using "html" tags like &lt;b|strong&gt; for bold or &lt;i&gt; for italic.

Example:
```php
$pdf->ezText("Hello <strong>World</strong> and <i>Universe</i> and both <i><b>BoldItalic</b></i>");
```

**Comment by rokyed** [comment]
I see, my tiny issue is that, the font doesn't stay selected, why is so? 
In my document, the font is still Helvetica, when Roboto should be instead.

Thanks.

**Comment by rokyed** [comment]
@ole1986 It seems the font automatically resets itself:

```bash
[05-Jan-2017 16:31:10 America/New_York] {"BEFORE":"","numFonts":1,"currentFont":"","currentBaseFont":"Roboto-Regular"}
[05-Jan-2017 16:31:10 America/New_York] {"AFTER":"","numFonts":1,"currentFont":"Roboto-Regular","currentBaseFont":"Roboto-Regular"}
[05-Jan-2017 16:31:10 America/New_York] {"BEFORE":"","numFonts":2,"currentFont":"Roboto-Regular","currentBaseFont":"Helvetica"}
[05-Jan-2017 16:31:10 America/New_York] {"AFTER":"","numFonts":2,"currentFont":"Helvetica","currentBaseFont":"Helvetica"}
[05-Jan-2017 16:31:10 America/New_York] {"BEFORE":"","numFonts":2,"currentFont":"Helvetica","currentBaseFont":"Helvetica"}
```

```php
	protected function setCurrentFont() {
			error_log(json_encode(array(
				"BEFORE"=>"",
				"numFonts" =>$this->numFonts,
				"currentFont" => $this->currentFont,
				"currentBaseFont" => $this->currentBaseFont,
			)));
			parent::setCurrentFont();
			error_log(json_encode(array(
				"AFTER"=>"",
				"numFonts" =>$this->numFonts,
				"currentFont" => $this->currentFont,
				"currentBaseFont" => $this->currentBaseFont,
			)));
		}
```

any idea? Thanks :smile:

**Comment by rokyed** [comment]
i hacked it and i am forcing my font every addText ( because addText it resets the font to Helvetica) I expect the:
```php
   if (!$this->numFonts) { // maybe this is always true ( I am using php 7.1)
       $this->selectFont(dirname(__FILE__) . '/fonts/Helvetica');
   }
```

**Comment by ole1986** [comment]
can you confirm that you could not change any font in php 7? even not the core fonts?

**Comment by rokyed** [comment]
any font gets changed to Helvetica , that condition doesn't execute , so i am lost, I don't know what other part can execute the reset of font

**Comment by ole1986** [comment]
We need to investigate some time to test it properly on PHP7

**Comment by ole1986** [comment]
@rokyed I have tested this issue with version 0.12.30 on PHP 7.1 X86 (TS - thread safe / windows)

**Example (using FreeSerif) - Shows the FreeSerif font**
http://localhost:9000/examples/unicode.php

**Example (using Helvetica) - which of course cannot deal with unicode**
http://localhost:9000/examples/unicode.php?font=Helvetica
**Example (using Courier) - which of course cannot deal with unicode as well**
http://localhost:9000/examples/unicode.php?font=Courier

All examples properly changes the font

```
// LINE 2943 in Cpdf.php
if (!$this->numFonts) {
    $this->selectFont(dirname(__FILE__) . '/fonts/Helvetica');
}
```

If you want to use the html notation, you might use

```
$pdf->setFontFamily("FreeSerif", array(
	"b"=>"FreeSerifBold"
));
```

PLEASE NOTE: There is no *italic* available for FreeSerif, you might download the font yourself

**Comment by ole1986** [comment]
Closed, not reproducible
