### ISSUE TITLE
Implementation of Table Column Colours: Bug and Fix

### ISSUE THREAD

**Issue by Manuzza** [rospdf/pdf-php#52]
Hi,

As of the previous update the table column coloring is not working properly. The issue is that the array path used to detect the column bgcolor is wrong.

In Cezpdf.inc change these lines:

```
// color of the column is second choice
elseif(isset($options["cols"]) && isset($options["cols"][$colName]) && isset($options["cols"][$colName]["bgcolor"]) && is_array($options["cols"][$colName]["bgcolor"]))
  $rowColShading[] = array("x"=> $rowX, "y"=>$rowY, "width"=>$rowW, "color"=>$options["cols"][$colName]["bgcolor"]);
```
to

```
// color of the column is second choice
elseif(isset($options["bgcolor"]) && isset($options["bgcolor"][$colName]) && is_array($options["bgcolor"][$colName]) && (sizeof($options["bgcolor"][$colName]) == 3))
  $rowColShading[] = array("x"=> $rowX, "y"=>$rowY, "width"=>$rowW, "color"=>$options["bgcolor"][$colName]);
```

This addresses the issue.

**Comment by ole1986** [comment]
@Manuzza 
With your patch the `'cols' => array('num' => array('bgcolor' => array(1,10)))` is ignored afterwards.
Checkout example `table-enhancements.php`

So, what exactly does your patch do?! 
Please provide us with a detailed example to avoid further mistakes

Result (original):
![image](https://cloud.githubusercontent.com/assets/4850116/21780871/6f4acfaa-d6ad-11e6-808b-b3cf82ea65b0.png)

Result (your patch applied):
![image](https://cloud.githubusercontent.com/assets/4850116/21780893/8260dc88-d6ad-11e6-9653-657e744e0728.png)

**Comment by Manuzza** [comment]
Yes, my error. I misread the doco regarding the structure of the array for passing the column colours in. Please close this Issue as resolved.
