### ISSUE TITLE
Support for CMYK color

### ISSUE THREAD

**Issue by andersLAL** [rospdf/pdf-php#53]
For many years we've used this great library to, among other uses, create barcodes that are printed on our products. These need to be in the CMYK colorspace to avoid offset printing problems (only want the barcode to show up in the black print), and therefore we added two functions, setColorCMYK() and setStrokeColorCMYK() to Cpdf.php back in version 009. Most likely the code was found elsewhere at the time, but I no longer remember.

We recently upgraded to the lastest version, and had to re-add the functions (which still worked). It would obviously be beneficial for us to get CMYK support added officially, so hoping that's something that can be considered? I'll be happy to help out. 

Here are the two functions we've been using, not sure if the function names fit with the current conventions:
```php
    /**
     * sets the CMYK colour for stroke operations
     */
    public function setColorCMYK($c,$m,$y,$k,$force=0){
        if ($c>=0 && ($force || $c!=$this->currentColour['c'] || $m!=$this->currentColour['m'] || $y!=$this->currentColour['y'] || $k!=$this->currentColour['k'])){
            $this->objects[$this->currentContents]['c'].="\n".($c/100).' '.($m/100).' '.($y/100).' '.($k/100).' k';
            $this->currentColour=array('c'=>$c,'m'=>$m,'y'=>$y,'k'=>$k);
        }
    }
    /**
     * sets the CMYK colour for stroke operations
     */
    public function setStrokeColorCMYK($c,$m,$y,$k,$force=0){
        if ($c>=0 && ($force || $c!=$this->currentStrokeColour['c'] || $m!=$this->currentStrokeColour['m'] || $y!=$this->currentStrokeColour['y'] || $k!=$this->currentStrokeColour['k'])){
            $this->objects[$this->currentContents]['c'].="\n".($c/100).' '.($m/100).' '.($y/100).' '.($k/100).' K';
            $this->currentStrokeColour=array('c'=>$c,'m'=>$m,'y'=>$y,'k'=>$k);
        }
    }
```

**Comment by MonteShaffer** [comment]
Like you, I have been using R&OS for some time.  I would extend the old setup with some custom functions, including an overwrite to AddPNGFromFile, as I added the $angle rotation.

In addition, I have some helper functions to `function setHexColor($hex)` and `function setStrokeHexColor($hex)`

It would seem like, to me, the best "color" solution would embrace all of these aspects...  My "hex" functions could have a parameter of 'rgb' or 'cmyk' and call the classic functions, or your functions...

Below is my basic extension ... I have created functions to drawArrows, drawBorders, drawGradients specific to a project, but these disclosed functions are rather generic ...
```

include_once(_COMMON_PATH_."php/libs/pdf-php/src/Cezpdf.php");

class Mpdf extends Cezpdf 
	{
	
	public function __construct($paper='a4',$orientation='portrait', $type = 'none', $options = array())
		{
		parent::__construct($paper,$orientation,$type,$options);
		}
		
	public function ezGetY(){
        return $this->y;
    }
	public function mSetDy($dy)
		{
		$this->y += $dy;
		}
	public function mSetMargins($top,$bottom,$left,$right)
		{
		  // sets the margins to new values
		  $this->ez['topMargin']=$top;
		  $this->ez['bottomMargin']=$bottom;
		  $this->ez['leftMargin']=$left;
		  $this->ez['rightMargin']=$right;
		  // without moving to next page
		}
	public function mXY($x,$y)
		{
		# pdf's start in bottom left, we want to do our coordinates based on top left ...
			if($x >= 0)
				{
				$nx = $x;
				}
				else
					{
					$nx = $this->ez['pageWidth'] - abs($x);  # negative values are from right edge ...
					}
			if($y >= 0)
				{
				$ny = $this->ez['pageHeight'] - $y;
				}
				else
					{
					$ny = abs($y);  # negative values are from bottom edge ...
					}
		return array($nx,$ny);
		}
		

	public function setBothHexColor($hex)
		{
		$this->setStrokeHexColor($hex);
		$this->setHexColor($hex);
		}
	public function setStrokeHexColor($hex)
		{
		# stroke color
		$color = str_replace('#','',$hex);
			if(strlen($color)==3){$color=$color{0}.$color{0}.$color{1}.$color{1}.$color{2}.$color{2};}			
		$r = number_format(hexdec(substr($color,0,2))/255,4);
		$g = number_format(hexdec(substr($color,2,2))/255,4);
		$b	= number_format(hexdec(substr($color,4,2))/255,4);
			$this->setStrokeColor($r,$g,$b);
		}
	public function setHexColor($hex)
		{
		# fill color
		$color = str_replace('#','',$hex);
			if(strlen($color)==3){$color=$color{0}.$color{0}.$color{1}.$color{1}.$color{2}.$color{2};}		
		$r = number_format(hexdec(substr($color,0,2))/255,4);
		$g = number_format(hexdec(substr($color,2,2))/255,4);
		$b	= number_format(hexdec(substr($color,4,2))/255,4);
		$this->setColor($r,$g,$b);
		}
		
		
	
	}
	
```

**Comment by ole1986** [comment]
Thank to both of you.

Feel free to do a PR  so I can easily merge it
Otherwise I will do so, as soon as I switch to the rospdf project for short.

**Comment by ole1986** [comment]
@MonteShaffer is there a chance to get see your `AddPNGFromFile` once?

**Comment by MonteShaffer** [comment]
AddPNGFromFile had a rotation component that I gave you over on SF.  Basic object rotation, so it should also be applied to GIF ...

http://askubuntu.com/questions/433382/tesseract-ocr-engine-on-ubuntu-how-to

https://sourceforge.net/p/pdf-php/feature-requests/32/

**Comment by ole1986** [comment]
@MonteShaffer have we already merged it? cant remember now

**Comment by ole1986** [comment]
Ok I checked it once - addPngFromfile is already included with rotation...

So the setColor methods will be available for the next update.

Thank you again for your submissions.

**Comment by andersLAL** [comment]
Awesome, thanks for the quick response/fix! Got stuck with some other problems at work, never even got a chance to reply before everything was taken care of... So thanks again :)
