### ISSUE TITLE
$test option of addText did not work as expected

### ISSUE THREAD

**Issue by xpech** [rospdf/pdf-php#57]
Hi Team,
I'm a very old user of ezPdf, I'm trying to update from 0.9.

I use the $test option on addTextWrap() to get the real height needed to display a text. With the new lib, the text is really printed in the PDF ! What's the best new practice to get the height of a text bloc without drawing in the PDF ?

Best regards

**Comment by ole1986** [comment]
The method `$pdf->getFontHeight($fontSize)` may help you in the regard
