### ISSUE TITLE
Illegal string offset?

### ISSUE THREAD

**Issue by MonteShaffer** [rospdf/pdf-php#61]
#0 /data/web/common/php/libs/pdf-php/src/include/TTF.php(1064): ErrorHandler(2, 'Illegal string offset '44.0000000000'', '/data/web/common/php/libs/pdf-php/src/include/TTF.php', 1064, Array)

**Comment by ole1986** [comment]
same issue #46 ?
Can you reproduce it - Possible issue with the font

**Comment by ole1986** [comment]
It is possible the font itself does not probably contain the font tables.
Closing it, but please reopen when you have a font available which causes this issue
