### ISSUE TITLE
ezImage and Background Not Work

### ISSUE THREAD

**Issue by luizotavior** [rospdf/pdf-php#64]
Hello, I have been coming to this project for a long time and am experiencing problems when I insert images into my pdf, I have the same problem when I try to insert background into my page, I downloaded as latest versions and the error persists. Sometimes an image works on a PHP page of my pdf and at other times it does not work. I have already tested the examples that come with the project and they even cause errors and do not display some images and backgrounds.

**Comment by ole1986** [comment]
@luizotavior 

Can you please provide us with some more details about your Environment?
And also the PHP version as well as the image format you are trying?

An example script of the working / not working pdf output would also be VERY helpful.
Thank you

**Comment by luizotavior** [comment]
Hi @ole1986, My php is in version 7.0, I am using XAMPP and I also tested it on a WEB server which is version 7.2

**Comment by luizotavior** [comment]
**Below are some errors in the example imagem.php**

**examples/image.php**
<b>Warning</b>:  fopen(C:/temp/cachedTimes-Roman.php): failed to open stream: No such file or directory in <b>C:\xampp\htdocs\pdf-php-master\src\Cpdf.php</b> on line <b>2119</b><br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, boolean given in <b>C:\xampp\htdocs\pdf-php-master\src\Cpdf.php</b> on line <b>2120</b><br />
<b>Warning</b>:  fclose() expects parameter 1 to be resource, boolean given in <b>C:\xampp\htdocs\pdf-php-master\src\Cpdf.php</b> on line <b>2121</b>

**examples/background_color.php**
<b>Warning</b>:  fopen(C:/temp/cachedCourier.php): failed to open stream: No such file or directory in <b>C:\xampp\htdocs\pdf-php-master\src\Cpdf.php</b> on line <b>2119</b>
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, boolean given in <b>C:\xampp\htdocs\pdf-php-master\src\Cpdf.php</b> on line <b>2120</b>
<b>Warning</b>:  fclose() expects parameter 1 to be resource, boolean given in <b>C:\xampp\htdocs\pdf-php-master\src\Cpdf.php</b> on line <b>2121</b>


Different error appeared when I tried to access earlier

**Comment by ole1986** [comment]
@luizotavior the warning messages are possible because you do not have the temporary path C:\temp.
Try to create a folder C:\temp and make sure the xamp instance has access to it.

Or change temp path in the script on LINE 19: 
`    $pdf->tempPath = 'C:/temp';`

**Comment by luizotavior** [comment]
@ole1986 Oh, right, sorry. Thanks a lot for the help.
