### ISSUE TITLE
Text justification in tables is broken...

### ISSUE THREAD

**Issue by Manuzza** [rospdf/pdf-php#65]
This worked in the old (original) version. I have tested .27 and .32 and it fails in both.

When "left" justification is used on text in a table the left edge is neat and it looks correct.

When "right" justification is used the right edge is neat, but it overlaps the edge of the table.

When "full" justification is used on text in a table cell then both right and left edges have jagged text.

All justification modes OUTSIDE of tables work perfectly.

The right justification issue seems to be consistent (but I almost never right justify text in a table so never noticed it before).

From what I can work out there are two factors that cause the "full" justification issue:
1. The width of the available space for the text.
2. Whether the text has longer words in it that mean larger gaps between words when wrapping occurs.

Change the sample "Lorem Ipsum" text (which has some long words) to a paragraph with short words (like "The quick brown fox.."), and the problem goes away. The sample code has both paragraphs present for testing.

Widen the table column so it has more space to work with, and the problem goes away. In the sample code, use a larger value of $W.

Sample code is in the zip file, which created the attached PDF.

[example.pdf](https://github.com/rospdf/pdf-php/files/982563/example.pdf)

[generate.php.zip](https://github.com/rospdf/pdf-php/files/982567/generate.php.zip)

**Comment by ole1986** [comment]
Thank you for reporting.... 

seems that PDF command "Tw" is kept in memory (even in a new object).

right align in table is fixed so far.
full justification in table is pending....

**Comment by Manuzza** [comment]
Thank you!
