### ISSUE TITLE
New Issue (first occurence in 0.12.34)

### ISSUE THREAD

**Issue by Manuzza** [rospdf/pdf-php#69]
Sorry, but the latest release has created a new issue. Very simply, this works:

$PDF->ezText("&lt;b>&lt;u>Bold and Underlined&lt;/u&gt;&lt;/b&gt;");

and this does not:

$PDF->ezText("&lt;u&gt;&lt;b&gt;Bold and Underlined&lt;/b&gt;&lt;/u&gt;");

The second one produces the following error:

Notice: Undefined offset: 0 in pdf_0.12.34/Cezpdf.php on line 2196

The "underline" line is drawn from the bottom left of the PDF (0,0) to the end of the line. It only fails if the &lt;u&gt; tag is outside the bold tag.

A "&lt;u&gt;" tag on it's own is fine.

Please see attached sample code and generated PDF.

Murray.
[pdf_generate_underline.php.zip](https://github.com/rospdf/pdf-php/files/1017868/pdf_generate_underline.php.zip)
[underline.pdf](https://github.com/rospdf/pdf-php/files/1017869/underline.pdf)

**Comment by ole1986** [comment]
should be fixed in version 0.12.35
