### ISSUE TITLE
Document properties garbled by setEncryption

### ISSUE THREAD

**Issue by VoiceInterface** [rospdf/pdf-php#70]
Document properties don't make it through intact when using 40-bit or 128-bit encryption. For example:

$pdf->addInfo('Title', 'Document title here');
$pdf->addInfo('Subject', 'Document subject here');
$pdf->setEncryption($upwd,$opwd,array('copy','print'),2);

produces a document title of "Dª÷%["yˆPÔx-r".   
comment out the setEncryption line and it is correct.

Using version 0.12.36 of the library and viewing the generated PDF with Adobe Acrobat Reader DC (2017.009.20044)

I have not attempted this with the 0.13 branch.

Bug?

(Loving the class so far.  Thanks to all the contributors.)

**Comment by ole1986** [comment]
Thanks for reporting - I will have a closer look into it soon..

**Comment by ole1986** [comment]
fixed in version 0.12.37

**Comment by ole1986** [comment]
I am so sorry.. I missed some special chars which will be fixed in 0.12.38

**Comment by ole1986** [comment]
Fully fixed in 0.12.38

**Comment by VoiceInterface** [comment]
Thanks!  Fantastic, responsive software support!
