### ISSUE TITLE
Massive performance decrease in 0.12.35+ addText/getDirectives when ezTable column is too narrow

### ISSUE THREAD

**Issue by andersLAL** [rospdf/pdf-php#71]
Had a very weird issue where PDFs that we had been creating without any problems for years would suddenly timeout after 2-3 minutes. They used to take about 10-15 seconds to generate. After a lot of investigation I eventually tracked it down to a combination of R&OS PDF 0.12.35 and a table column that is slightly to narrow.

Difficult to explain in more detail, so a reduced test file is attached along with xdebug dumps of both 0.12.34 and 0.12.35 (issue also exists in 0.12.38). Changing the width of the column from 50 to 55 (line 27 in the test.txt - rename to .php) avoids the issue.

Screenshots from Cachegrind (with width = 50):
0.12.34
![0 12 34_addtext](https://user-images.githubusercontent.com/25003890/27727330-55a96b6c-5d7e-11e7-8ef3-0a21c2cad083.jpg)
![0 12 34_getdirectives](https://user-images.githubusercontent.com/25003890/27727328-55a5c4b2-5d7e-11e7-95a0-3438418e5f24.jpg)

0.12.35
![0 12 35_addtext](https://user-images.githubusercontent.com/25003890/27727329-55a7a0a2-5d7e-11e7-81ab-511198d0fed5.jpg)
![0 12 35_getdirectives](https://user-images.githubusercontent.com/25003890/27727331-55ada3c6-5d7e-11e7-8a18-2ae81647fc47.jpg)

[test.txt](https://github.com/rospdf/pdf-php/files/1114537/test.txt)
[xdebug.zip](https://github.com/rospdf/pdf-php/files/1114534/xdebug.zip)

**Comment by ole1986** [comment]
Really good bug report - thank you for this.
I assume you are running this on linux / mac.

Can you please provide me with some more details about the php version (phpinfo() if possible)?

**Comment by ole1986** [comment]
will be fixed in version 0.12.39

**Comment by andersLAL** [comment]
Awesome, thanks! Will test it at work on Monday. Probably not relevant any longer, but I run it on FreeBSD, PHP 7.1.<something>. Will include that next time.

Had a hard time understanding the addText and getDirectives methods, otherwise I would have tried to track it down further :)

**Comment by andersLAL** [comment]
Worked perfectly, thanks for the quick fix!
[xdebug.0.12.39.zip](https://github.com/rospdf/pdf-php/files/1119044/xdebug.0.12.39.zip)
