### ISSUE TITLE
Protected Function

### ISSUE THREAD

**Issue by Manuzza** [rospdf/pdf-php#73]
Not really a bug per se - more of a question...

Is there any reason why the following function is defined as protected?

protected function addImage(&$img, $x, $y, $w = 0, $h = 0, $quality = 75, $angle = 0)

It is not used from anywhere else in the class and being protected, it cannot be access from outside the class. Shouldn't this be defined as public in order for it to be usable?

Murray

**Comment by ole1986** [comment]
Hi Manuzza,

I am surprise this function is not used (even not in Cezpdf).
So putting the method on public should gives the develop the option to use gd features, like `imagestring`.

Example:
```
// http://php.net/manual/de/function.imagejpeg.php
$im = imagecreatetruecolor(120, 20);
$text_color = imagecolorallocate($im, 233, 14, 91);
imagestring($im, 1, 5, 5,  'A Simple Text String', $text_color);

$P->addImage($im, 600,500)
```

I will change this to a public method and include an example on how to use gd.
Thank you for reporting
