### ISSUE TITLE
Inserting footer text (position text vertically)

### ISSUE THREAD

**Issue by chros73** [rospdf/pdf-php#74]
Hi!

First of all thanks for this amazing class!
I've upgraded your classes couple of days ago from v009 (5-6 years old! :) ) and I noticed that I can't position text vertically. It worked like this before (I mean a long-long time ago):
```php
$this->pdf->ezText($footer,6,array('justification'=>'center','atop' => 44, 'aleft'=>50, 'aright'=>545.28));
```
There was an `atop` property. This line is called froma addFooter function that added the $footer at the bottom of every page.
How can I achieve the same thing now?

Thanks

**Comment by ole1986** [comment]
I could not find any atop in the previous versions.
But of course you can send me your complete ezText method so we can recover it.

Thank you

**Comment by chros73** [comment]
Thanks for the reply.
Actually I couldn't find it either in the v009 source that I downloaded from somewhere.
That makes tell me that maybe we modified your code at that time to be able to use `ezText` instead of `addText` to place multiline justified text in the footer.

I ended up modifying `ezText` in cezpdf class to include this "atop" property (based on our old code): it's just couple line of change.
If you are interested I can create a pull request.

Sorry for the misinformation.

**Comment by ole1986** [comment]
Absolutely yes,

feel free to create a PR and I am going to check and merge it.
Thank you Sir!

**Comment by chros73** [comment]
We thank you for your work! :)
I'll create a pull request this evening (I can't do it from work).

Can you create new example script for it later? (I don't have time nowdays, and we use an abstraction class with it in our code):
- add 2 pages
- set margains
- add sample text to both pages
- add footer to both pages
  - draw a line in footer
  - add page numbers, form: x - y
  - add multiline text in the footer
	- position it center

The code should look like this:
```php
$this->pdf = new cezpdf('a4', 'portrait');
$this->pdf->ezSetMargins(100,80,50,50);
// ...
// footer
$this->pdf->setLineStyle(1);
$this->pdf->setStrokeColor($colour['R'],$colour['G'],$colour['B']);
$this->pdf->line(50,40,545.28,40);
$this->pdf->ezStartPageNumbers(540,34,6,'','Page {PAGENUM} of {TOTALPAGENUM}',1);
$this->pdf->ezText($footer,6,array('justification'=>'center','atop' => 44, 'aleft'=>50, 'aright'=>545.28));
```
