### ISSUE TITLE
Pb with accents with new version of class

### ISSUE THREAD

**Issue by mathias1981** [rospdf/pdf-php#85]
hello,
I was using an old version of the ezpdf class. I just updated it to the latest so to use it with PHP7, and i have a problem, all letters with accents are not well encoded. I saw the issue number 50, where you advice to use the utf8_encode fuction.

Problem is that i have tons of pdf files generated, with text within it in several places and it is impossible to encode each text in all the pdf. 

Isn't there an easiest way to make the encoding work well for each pdf file declaring for instance a charset at the top of the pdf file instead of encoding each text?

**Comment by ole1986** [comment]
Hi @mathias1981 

possibl< you can  `$pdf->isUnicode = true` before any selectFont

**Comment by mathias1981** [comment]
Hi @ole1986 
Thank you for your fast answer. This does not work, if i do not do utf8_encode() for the text in the tables and in the addtext function, i get "?" instead of the accents
