### ISSUE TITLE
formatType is 0.0

### ISSUE THREAD

**Issue by interduo** [rospdf/pdf-php#86]
I am using 0.12.41 version.

rospdf/pdf-php/src/include/TTF.php[651]: Internal error - formatType is 0.0

Got an error when generating documents in CRM. 
How to debug that?

**Comment by ole1986** [comment]
Possible is that the font you are trying has no proper info or has an incompatible format.
Can you tell me which font you were trying?

**Comment by interduo** [comment]
I turn on debbugging and see also:

Warning: Division by zero in rospdf/pdf-php/src/Cpdf.php on line 1950
Warning: Division by zero in rospdf/pdf-php/src/Cpdf.php on line 1951
Warning: Division by zero in rospdf/pdf-php/src/Cpdf.php on line 1952
Warning: Division by zero in rospdf/pdf-php/src/Cpdf.php on line 1953

 I am using Helvetica.

**Comment by ole1986** [comment]
Helvetica is usually a core font...  So there shouldnt be a reason to use TTF.php.
Can you come up with a reproducible example script?

**Comment by interduo** [comment]
`Fatal error: Uncaught Error: Call to undefined function bcadd() in /var/www/html/lms/vendor/rospdf/pdf-php/src/include/TTF.php:1168 Stack trace: #0 /var/www/html/lms/vendor/rospdf/pdf-php/src/include/TTF.php(54): TTF::getUlong('\x00\x01\x00\x00\x00\x17\x01\x00\x00\x04\x00pDSI...', 16) #1 /var/www/html/lms/vendor/rospdf/pdf-php/src/Cpdf.php(1908): TTF->__construct('\x00\x01\x00\x00\x00\x17\x01\x00\x00\x04\x00pDSI...') #2 /var/www/html/lms/vendor/rospdf/pdf-php/src/Cpdf.php(2143): Cpdf->openFont('arial') #3 /var/www/html/lms/lib/LMSDocuments/LMSEzpdfBackend.php(85): Cpdf->selectFont('arial', Array, 1, true) #4 /var/www/html/lms/lib/LMSDocuments/LMSDocument.php(33): LMSEzpdfBackend->__construct('A4', 'landscape', 'Formularz przel...') #5 /var/www/html/lms/lib/LMSDocuments/LMSEzpdfTransferForm.php(31): LMSDocument->__construct('LMSEzpdfBackend', 'Formularz przel...', 'A4', 'landscape') #6 /var/www/html/lms/modules/transferforms.php(68): LMSEzpdfTransferForm->__construct('Formularz przel...', 'A4', 'landscape') #7 /var/www/htm in /var/www/html/lms/vendor/rospdf/pdf-php/src/include/TTF.php on line 1168`

And the script /var/www/html/lms/modules/transferforms.php is here: 
https://github.com/lmsgit/lms/blob/master/modules/transferforms.php

**Comment by interduo** [comment]
Do You know what is the purpose of the bug and how to repair it?
I upgraded to 0.12.43 and the bug also occurs.

**Comment by ole1986** [comment]
Either the TTF parser cannot properly analyse the font or the font header info is corrupted I guess

**Comment by chilek** [comment]
@interduo sometimes helps deleting all cached font structures in /tmp directory (/tmp/cached*.php).

**Comment by ole1986** [comment]
That is also true, if by mistake a font has been loaded the corrupt content may persist in the cached font files.

So deleting them can be very helpful.

**Comment by interduo** [comment]
It doesn't help. 

Did update today, this still occurs in the newest version.

[Fri May 11 12:18:58.382836 2018] [:error] [pid 8653] [client 172.20.2.42:49818] PHP Fatal error: Uncaught Error: Call to undefined function bcadd() in /var/www/html/lms/vendor/rospdf/pdf-php/src/include/TTF.php:1168\nStack trace:\n#0 /var/www/html/lms/vendor/rospdf/pdf-php/src/include/TTF.php(54): TTF::getUlong('\\x00\\x01\\x00\\x00\\x00\\x17\\x01\\x00\\x00\\x04\\x00pDSI...', 16)\n#1 /var/www/html/lms/vendor/rospdf/pdf-php/src/Cpdf.php(1913): TTF->__construct('\\x00\\x01\\x00\\x00\\x00\\x17\\x01\\x00\\x00\\x04\\x00pDSI...')\n#2 /var/www/html/lms/vendor/rospdf/pdf-php/src/Cpdf.php(2148): Cpdf->openFont('arial')\n#3 /var/www/html/lms/lib/LMSDocuments/LMSEzpdfBackend.php(85): Cpdf->selectFont('arial', Array, 1, true)\n#4 /var/www/html/lms/lib/LMSDocuments/LMSDocument.php(33): LMSEzpdfBackend->__construct('A4', 'landscape', 'Formularz przel...')\n#5 /var/www/html/lms/lib/LMSDocuments/LMSEzpdfTransferForm.php(31): LMSDocument->__construct('LMSEzpdfBackend', 'Formularz przel...', 'A4', 'landscape')\n#6 /var/www/html/lms/modules/transferforms.php(68): LMSEzpdfTransferForm->__construct('Formularz przel...', 'A4', 'landscape')\n#7 /var/www/htm in /var/www/html/lms/vendor/rospdf/pdf-php/src/include/TTF.php on line 1168, referer: https://lms.interduo.pl/?m=print&type=transferforms&kind=2

**Comment by interduo** [comment]
I installed on my debian php-bcmatch. The error doesn't occurs.

**Comment by ole1986** [comment]
I highly appreciate your effort and thank you for reporting it to us.
