### ISSUE TITLE
Problems with character "-" (dash). PDF not displayed

### ISSUE THREAD

**Issue by mathias1981** [rospdf/pdf-php#88]
Hello,

When inside a table i have a text with a dash (-), the table is not displayed at all and it stops the display of all the content coming after.

Any idea?

Regards

**Comment by ole1986** [comment]
possible line wrapping issue.
would you be so kind and build up an example page?

**Comment by mathias1981** [comment]
Hello,
I tried but do not manage to do a simple example. The code is inside a whole PHP code, that cannot be copied or duplicated easily. Is there a way to have a "debug" mode, so to identify the problem?

**Comment by mathias1981** [comment]
Maybe that can help, i have another problem with another PDF, which seems to be related to the breakline. Indeed, when i do not output the pdf, i get the folowing error :
Undefined offset: 8203 dans Cpdf.php à la ligne 3301 which corresponds to :  $breakWidth = ($w - $this->fonts[$cf]['C'][$cOrd]) * $size / 1000;

Any idea?

**Comment by ole1986** [comment]
have you checked the dash is a dash? not any other utf character which may not be in the font you have choosen?.

Btw what font is selected?

**Comment by mathias1981** [comment]
I'm using Helvetica. No, it looks like there is not another UTF char, i have problems sometimes, even when there is not a dash. The error i gave you on line 3301 is for a PDF which does not include any special char

**Comment by ole1986** [comment]
Which version you are using? Latest?

**Comment by mathias1981** [comment]
yes, last version of the github

**Comment by mathias1981** [comment]
Hello,
Sorry i did not updated sooner. I investigated and found out that if i change the font the pdf are displaying correctly : Helvetica is not working but courrier and Times-roman are working.
Any idea of what the problem may be with helvetica?

**Comment by ole1986** [comment]
Hi,
helvetica is a core found... ther might be some error in the *.afm file.
But that file is actually not change since a while....

can you please come up with an example code, esspacially the method(s) you are using (incl. justifications, etc..)?

**Comment by mathias1981** [comment]
It is very difficult for me to provide you an example, because the code is generated in a very large php file, which do a lot of operations before generating the pdf code.
But i have a new information : it comes out that when i go back to helvetica, and reduce the size of the font in the tables, it solves the problem very often.
So i have the impression that the problem sounds like a text too large inside a row and column which causes a crash of the pdf. 
Does that help you find the problem?
Thanks again!

**Comment by Manuzza** [comment]
In my experience with large amounts of text the table width auto-calculation can sometimes produce a column so narrow content does not fit. So It keeps adding pages forever trying to make it fit until it runs our of available RAM or PHP hits the time limit (whichever comes first). Increasing either of those does NOT solve the problem.

Try the "evenColumns" setting for debug purposes and then try setting the widths for your columns manually (set the widths for the table and for all the narrow columns and do not set the width for the one with the most content - it will auto fit into the available space).

Note that if there are way too many columns of content it may be that it simply does not fit. When a web browser has this problem it solves it simply by adding horizontal scroll bars. No equivalent fix exists for PDF generation which has a clearly defined width available.

**Comment by ole1986** [comment]
I am still testing this on another local branch

**Comment by mathias1981** [comment]
i found a solution! Putting more column gap in the options solved the problem...
Regards
